# Generated by Django 5.1.5 on 2025-04-06 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 6, 18, 11, 44, 274550, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
